### PR TITLE
✨Nord Theme for ct.js

### PR DESCRIPTION
**Pull request by ghost**
***Changes proposed in this pull request:***
- Adds a new UI theme, called "Nord" that uses the [nordtheme](https://nordtheme.com) color pallete, an arctic north-bluish color palette with beautiful and harmonic color contrasts
- Adds a new Monaco Editor Theme, called "Nord", with syntax colors that give optimal focus and readability

***Ping the Maintainer***
Time To Ping The Great, Almighty, Emperor of ct.js: @CosmoMyzrailGorynych

***Screenshots of ct.js with this theme enabled can be found below:***
image
image
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
@CosmoMyzrailGorynych I have fixed the licensing errors you discussed on discord, and also a few other minor errors.

**Review by ghost — COMMENTED** [review]
Fixed syntax color inconsistencies

**Comment by ghost** [comment]
Fixed all errors, edited nordtheme to use nord highlight.js style, and nordtheme is now ready to merge!

**Review by CosmoMyzrailGorynych — APPROVED** [review]
Looks good 👍

**Pull request merged**
