### PR TITLE
:sparkles: Editor zooming

### PR DESCRIPTION
**Pull request by amsam0**
**Changes proposed in this pull request:**

- Editor zooming

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
image
# *WHAM*

**Comment by CosmoMyzrailGorynych** [comment]
Scaling the window to `NaN` breaks the editor. The max zoom factor is 5 and should not overflow here too. I also think that these controls should change the zoom factor by `0.1`, for more fine-grained control, especially on smaller screens, and that the value should be saved in `localStorage`.

image (courtesy of Discord)

Also, please use `camelCase` instead of `snake_case` in JS. (`window.languageJSON.common.zoom_out`, `window.languageJSON.common.zoom_in`.)

**Comment by amsam0** [comment]
Thanks for the feedback! I will change this soon. I didn't look at the documentation that much, I also need to see how to use localStorage. As for camel case, I wasn't really sure what to use but I should of looked at the text. Probably spent too much time with Python

**Comment by CosmoMyzrailGorynych** [comment]
localStorage is a key-value persistent object, you just write to it with `localStorage.myPreciousZoomSetting = 2;`. The thing to remember is that it stores strings only, and thus everything gets converted. You should convert strings back to numbers (e.g. `Number(localStorage.someSetting)` to avoid the famous JS weirdness `'1' + 0.25 = 10.25`.

**Comment by amsam0** [comment]
~~Is localStorage available outside the ide? I didn't see that in the documentation~~

**Comment by amsam0** [comment]
Could you take another look? I'm pretty sure it's ready to be merged.

**Comment by CosmoMyzrailGorynych** [comment]
Fixed a first-launch bug, shrunk the code a bit, aaand — done! :tada:

**Review by CosmoMyzrailGorynych — APPROVED** [review]

**Pull request merged**
