### PR TITLE
⚡  Lossless Image Optimization

### PR DESCRIPTION
**Pull request by FlipFloop**
While I figure out how to contribute on M1.
ImageOptim was the app used.

Before sending the pull request, make sure that:

- [ ] `gulp build` runs without issues.
- [x] if you develop a catmod, a test project and docs are also present. Put a test project into a catmod's directory.
- [x] if it is a work-in-progress, explicitly mark it as such in the title with the `WIP: ` prefix.
- [x] The title of the pull request has a suitable emoji from [the Comigoji guide](https://comigo.gitlab.io/comigoji/#gitmoji). The title *will* look broken on GitHub, but it streamlines further merging and makes writing a pretty changelog easier.

--------------------------------------------------------

Closes #(issue's index).

**Changes proposed in this pull request:**

- Use [ImageOptim](https://imageoptim.com/mac) to perform lossless optimization on all images.

**Help wanted:** (optional, e.g. a request for GUI revamp)

- Build this as I have an M1 chip.

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by markmehere** [comment]
Isn't this what you're after #368 ?

Be great to get some feedback on it. Should be a simple `npm install` and then `npm start`.

**Review by markmehere — APPROVED** [review]
Works! 🎉 Seems like a good idea. Haven't compiled to see exactly how much this shaves off the builds but I'm happy with it.

**Comment by FlipFloop** [comment]
@markmehere Probably very little. I think it saved some 10mb lmao.

**Review by CosmoMyzrailGorynych — APPROVED** [review]

**Review by CosmoMyzrailGorynych — APPROVED** [review]

**Comment by CosmoMyzrailGorynych** [comment]
How come I approved it twice

**Comment by CosmoMyzrailGorynych** [comment]
Maybe we will need a build task for this in the future

**Comment by FlipFloop** [comment]
@CosmoMyzrailGorynych What do you mean? Also I think Github actions can do what this PR did on build.

**Comment by CosmoMyzrailGorynych** [comment]
That's exactly what I mean.
We use Gitlab CI instead of Github actions.

**Comment by FlipFloop** [comment]
So @CosmoMyzrailGorynych are you asking me to integrate image processing in the repo through GitLab CI? Also, how come that runs there and not here.
More on this, do we perform minification of Game Assets (Image processing/optimization) when building/exporting a game?

**Comment by CosmoMyzrailGorynych** [comment]
> are you asking me to integrate image processing in the repo through GitLab CI?

It would be great, but I was just thinking out loud before.
For ct.js builds, we have Gitlab CI. Period. GH actions can be added for PRs, regular commits and such, but ct.js' build pipeline stays where it is now.

>  More on this, do we perform minification of Game Assets (Image processing/optimization) when building/exporting a game?

No, ct.js currently doesn't do it.

**Pull request merged**
