### PR TITLE
:zap: Multiple input methods can be selected/added at once.

### LINKED ISSUE #260: Ability to add multiple input methods at once
**Is your feature request related to a problem?**
I think the workflow of adding input methods could be smoother by an ability to add multiple input methods at once instead of selecting and then re-opening the "Add an input method" dialog for each method.  For instance when adding methods for a specific axis, usually there are multiple for each direction.  

**Describe the solution you'd like**
Maybe a checkbox next to each input method you'd like to add?

**Describe alternatives you've considered (optional)**
Any way of highlighting multiples I think would be an improvement.

### PR DESCRIPTION
**Pull request by dtgreene**
Closes #260 .

**Changes proposed in this pull request:**
- Users can select and add multiple input methods at once

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by dtgreene** [comment]
If interested, I've also got an addition I can add  that uses checkboxes instead of background highlighting as well as showing the number of items selected:
image

**Comment by CosmoMyzrailGorynych** [comment]
@greeneman42 Checkboxes look nice and intuitive, why not. I would prefer them over the background color. It also would be cool if users could select new methods and deselect the old ones in the same dialog.

I think the length of the selection can be put in the button "Select", so we have "Select 5" label with five ticked elements.

**Comment by dtgreene** [comment]
@CosmoMyzrailGorynych Okay sweet! I'll make the changes and update this request

**Comment by dtgreene** [comment]
@CosmoMyzrailGorynych okay this is how it looks after the most recent commit.  I think this is what you were talking about
image

**Comment by CosmoMyzrailGorynych** [comment]
Buggy; the representation differs from the model. Looking for the cause rn…

изображение

**Comment by CosmoMyzrailGorynych** [comment]
So,

The issue appeared because the `checked="{selectedMethods.indexOf(module.code+'.'+code) > -1}"` was added to a label, not to an input.
There was also a minor issue with visually clickable zones at the top and bottom of a menu entry that did not trigger the events, so I edited the layout a bit to make the whole menu item clickable.
Finally, I added a condition to avoid adding duplicates.

**Review by CosmoMyzrailGorynych — APPROVED** [review]

**Comment by dtgreene** [comment]
Ah, I should have caught that about the checked on the label.  Sorry about that.  Hope it wasn't too much hassle

**Comment by CosmoMyzrailGorynych** [comment]
No one is perfect ¯\\\_(ツ)_/¯ Especially on their first try.
I'll wait for Travis and will merge the PR. Oh, it has just compeled.

**Comment by 68595959** [comment]
-_0

**Pull request merged**
