### PR TITLE
[WIP] :sparkles: Actions, EmitterTandems, Rooms, Scripts, Skeletons, Sounds…

### PR DESCRIPTION
**Pull request by amsam0**
…, Styles, Textures, and Types are stored in seperate files

Dosen't really close anything, but it's related to #75.

**Changes proposed in this pull request:**

- `.ict` files are now partially separated, hopefully making collaboration easier.

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by amsam0** [comment]
Bug: Script order is lost.

**Comment by CosmoMyzrailGorynych** [comment]
This is not final, right? Can't see the code that loads separate files back

**Comment by CosmoMyzrailGorynych** [comment]
The core idea of the file-based approach is removing the game model (its project data) from memory to files, and loading/unloading them when needed. This will allow working on really big projects with limited memory. (And it is important for the smaller projects as well! Potato devices are always in need haha)

In practice, current asset lists will search for asset names not in currentProject, but file folders. I recommend writing helpers to get a folder's resources and turn them into arrays edible by the `asset-viewer` tag. I think it will be best to pass the paths of asset files to editors as well. This should better have separate methods like `openRoom`, `openTexture` to ease the further migration to the multi-tabbed layout.

(You have a nice, geniusly lazy project conversion here!)

**Comment by amsam0** [comment]
This is not at all final, I made this before reading the Google Doc. I will use it to start on the concepts in the Google Doc, I was thinking a loop + a switch expression for saving/loading. I can close it if it's not needed.

**Comment by amsam0** [comment]
I'm going to close this and make a new pr for the new branch.

**Pull request closed without merging**
