### PR TITLE
⚡ Desktop features Catmod: New Features & Rewrite of Previous Features

### PR DESCRIPTION
**Pull request by ehanahamed**
Does not close any issues.

**Changes proposed in this pull request:**

- **Rewrote the already existing `quit()` method to use electron's ipc instead of electron remote**
  - [remote is depreciated](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-140) and [it's replacement](https://www.npmjs.com/package/@electron/remote) is unstable and recommends ipc instead. (more specifically [ipc.invoke](https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrendererinvokechannel-args) & [ipc.handle](https://www.electronjs.org/docs/latest/api/ipc-main#ipcmainhandlechannel-listener)) 
    - To quote from [Electron Docs - References - Breaking Changes](https://www.electronjs.org/docs/latest/breaking-changes):
    - > The remote module was deprecated in Electron 12, and will be removed in Electron 14. It is replaced by the [@electron/remote](https://github.com/electron/remote) module.
    - For context: As of right now, Electron's latest stable release is v19.0.8 and Electron v14 (mentioned in the quote) has already removed the remote module from electron. The quote mentions that the removed built-in module can be used from a separate replacement module: @electron/remote.
    -  To quote from [@electron/remote](https://www.npmjs.com/package/@electron/remote):
    - > ⚠️ Warning! This module has [many subtle pitfalls](https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31). There is almost always a better way to accomplish your task than using this module. For example, [ipcRenderer.invoke](https://www.electronjs.org/docs/api/ipc-renderer#ipcrendererinvokechannel-args) can serve many common use cases.
    - Thus, the most future-proof, modern, and conventional option is using ipc.
    - Note that the functionality in nw.js has not changed
- **Added more functions and methods,** using the same functionalities explained above
- **Added documentation listing the many new features**
- **Made changes in `./app/data/ct.release/desktopPack/ctGame.js`** in order for the functionalities above (such as ipc) to work.

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by ehanahamed** [comment]
An example ct.js project (made in packaged v2.0.2) to test all of the functions, methods, and properties in the catmod is attached below! 🧐🧐

[desktopCatmodTest.ict.zip](https://github.com/ct-js/ct-js/files/9185819/desktopCatmodTest.ict.zip)

**Review by CosmoMyzrailGorynych — CHANGES_REQUESTED** [review]
This code is MOIST.

I think it would be better to generalize the way ct.js games send data back into the background process by making a function that returns new functions, as "we can't do X in ct.js" and the sent command are the only two things by which all these methods differ. Otherwise, a function that validates the environment before sending the IPC call could be used to keep the code DRY.

Besides that, could you also add a method to get whether a game is currently in the fullscreen mode? I guess it will return a Promise<boolean> with all this IPC stuff :thinking:

**Comment by ehanahamed** [comment]
> This code is MOIST.

Yes here in the northeast americias we have very humid weather during the summer, its really annoying and causes everything to become really moist. I guess the same applies with code written here. 🤣 🤣 

> I think it would be better to generalize the way ct.js games send data back into the background process by making a function that returns new functions, as "we can't do X in ct.js" and the sent command are the only two things by which all these methods differ. Otherwise, a function that validates the environment before sending the IPC call could be used to keep the code DRY.

Hmmm, good idea. I'll implement this as soon as I can! 😃😃

Maybe in the future it might be feasible to make catmods able to add injections into the electron main process, like they can with the html of ct.js exports, but for right now your explanation seems to be the more rational option!

> Besides that, could you also add a method to get whether a game is currently in the fullscreen mode? I guess it will return a Promise with all this IPC stuff 🤔

Good idea, I'll also implement some other methods that return certain states of features such as weather devtools is open, weather the window is minimized, ect.

**Comment by ehanahamed** [comment]
@CosmoMyzrailGorynych I believe this PR is now ready for merging, I've fixed all adressed issues and have added requested additions! Good Night/Day!

**Review by CosmoMyzrailGorynych — APPROVED** [review]
Ooooh, that's interestiiing!
What a cool way to support both nw.js and electron! I like it!

**Pull request merged**
