### PR TITLE
:sparkles: Support for Apple Silicon builds

### PR DESCRIPTION
**Pull request by markmehere**
Great news! This pull request now produces Mac OS X ARM builds on Linux (tested with Ubuntu 22.04 running in VirtualBox).

Some parts like itch.io deployments, GitHub deployments and nightly builds remain untested and everything should be reviewed before merge.

The PR aims to behave gracefully if the ARM build fails - which may happen as all nw.js ARM builds are unofficial courtesy of @corwin-of-amber. https://github.com/corwin-of-amber/nw.js/

To ensure security (from me) I have now locked my custom `nw-builder-arm` package to a particular release rather than the tip of a branch.
 
This `nw-builder-arm` package forks `nw-builder` to pull from @corwin-of-amber's release page. See the pull request for that fork at: https://github.com/markmehere/nw-builder/pull/1

Excluding the `package-lock.json`, this pull request is really only a breezy 53 new lines and the `nw-builder` fork is only an extra 62 (excluding `lib/index.cjs`). The big line count change in `lib/index.cjs` occurs because the fork turns off minification to allow for easy debugging and commit diff viewing. 

The latest version of this pull request fixes some issues so that it now works for both **ARM builds** and **ARM runs** (via `npm start`/`gulp`).

As previously discussed, Ct.js works on Apple Silicon and works well. The x64 Intel builds do as well but aren't as snappy or battery efficient (intense users also report problems [see here](https://github.com/nwjs/nw.js/issues?q=is%3Aissue+is%3Aopen+Mac)).

Official support remains held up by Nw.js's lack of build hardware and doesn't look to be getting resolved anytime soon. https://github.com/nwjs/nw.js/issues/7620

apple-silicon-build

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
> This pull request hacks nw-builder to pull from @corwin-of-amber's release page. https://github.com/markmehere/nw-builder/pull/1

But is it needed? `nw-builder` has options to check versions and download files at different URLs.
image

I had to use custom builds before and documented the actions needed to do so here: https://github.com/ct-js/ct-js/blob/develop/gulpfile.js#L29

Could you fiddle with these parameters? I guess a custom manifest in a github repo will be needed. But if it will be possible with a regular `nw-builder` package, we can modify the `gulp packages` pipeline to build both regular and Apple Silicon builds, with different settings.

**Comment by markmehere** [comment]
Even with a custom manifest (see the manifest [here](https://nwjs.io/versions.json)) NW-Builder still has no concept of what `osx-arm64` is. The manifest also doesn't specify the file name and while you can provide a download URL it's meant to be one that provides all builds. So even if you were to go to the trouble of the custom manifest and relocating all builds, you would still run into issues because NW-Builder doesn't know, for example, the `arm64` runnable is at:

```
    getRunnable: function(version) {
        return "nwjs.app/Contents/MacOS/nwjs";
    }
```

So I still feel you're going to need some level of customisation or sway with the NW-Builder team. This PR though should prove help if any new developers with an M1/M2 Mac come on board. The [hack PR](https://github.com/markmehere/nw-builder/pull/1) can also be cleaned up or based off a specific version of NW-Builder. I'd also ideally like to call the build `osxarm` instead of `osxm1`.

**Comment by CosmoMyzrailGorynych** [comment]
Then two nw-builder packages it is! It's node.js, we can use both versions

**Comment by markmehere** [comment]
Yeah there is a way to do this neater. Especially as I have control of the fork. I'll have a play around don't expect anything too soon though. 🙂

**Comment by markmehere** [comment]
@CosmoMyzrailGorynych I've now revisited this pull request and done a complete Mac OS X Apple Silicon zipped-build on Ubuntu 22.04 (took a lot of time to install Ubuntu). As such I think #370, #368 and #364 are all unblocked from my side and its over to you for whether they can be merged in.

This pull request incorporates #370 as I need working Mac versions to test the build.

If you have further changes, it may be a while until I'll get to them but I suspect will. Direct branch edits from you are fine too and given I don't have the ability to publish to itch/github may be necessary. 🙂

**Comment by CosmoMyzrailGorynych** [comment]
Sorry for leaving a broken build pipeline. I'm on a business trip and won't have much time or energy to review everything.

I was updating nw-builder in it back and forth before to see whether the pipeline works with new nw-builder versions.
There were several regressions in it, described here: https://github.com/nwutils/nw-builder/issues/641

Can you confirm that `gulp packages` work in your branch? Also, can you/do you want to work on https://github.com/ct-js/ct-js/issues/355 as well? The current problem, besides nw-builder regressions that now have workarounds, is that my image at https://github.com/ct-js/docker-nw-builder has a wrong version of Wine. (Or maybe it needs both x64 and x32.) I can give you write access to ct.js repos, or you can fiddle with your own Gitlab fork of ct-js/ct-js repo. (Or push directly to ct-js/ct-js on Github. I don't mind it.) If the pipeline completes `gulp packages` task, it is ready for itch.io.

**Comment by markmehere** [comment]
> Can you confirm that `gulp packages` work in your branch? 

The `gulp packages` does work! I tested it on Ubuntu - I'm still gun shy about building on Mac OS X because for some reason the build was able to mess up my Finder settings last time and really scared me. I'll take a look at the docker stuff a little later. No rush from my side on any of this stuff. Also I didn't check all packages just the ARM package - in theory none of the others changed - but I didn't test that. It was exhausting enough getting a working ARM build to my M1 Mac to test. 😁

**Comment by markmehere** [comment]
@CosmoMyzrailGorynych DevOps has never been a strong suit of mine. Although that probably is why it is probably one of the more valuable skills for me to work on...

Have a look at this and see if it makes any difference:

https://github.com/ct-js/docker-nw-builder/pull/1

**Review by FlipFloop — APPROVED** [review]

**Review by FlipFloop — APPROVED** [review]

**Comment by FlipFloop** [comment]
Any updates on this?

**Comment by markmehere** [comment]
@FlipFloop Should be good to go.

```
git fetch https://github.com/markmehere/ct-js.git apple-silicon-build:apple-silicon-build
git checkout apple-silicon-build
npm install
npm start
```

The problem @CosmoMyzrailGorynych is having is a build server issue with [WINE](https://www.winehq.org/) and [rcedit](https://github.com/electron/node-rcedit/blob/master/lib/rcedit.js#L9). Unless you're planning to run ct.js through [Docker](https://www.docker.com/) you should be unaffected.

But we could use confirmation that the build works for someone else. 🙌

**Comment by FlipFloop** [comment]
@markmehere It built. Seems to be working fine. I'll play around with it but so far, good to go!
I didn't realize how far ct.js came from 2.0, I'm glad to start working on it like I told myself a year ago :)

**Comment by markmehere** [comment]
@FlipFloop Feel free to have a look at some other pull requests. Not everything needs to go in or get approval. Sometimes the best part is what you leave out. Even though nobody except Cosmo can merge. Sometimes a different perspective is helpful to get things in (or out) quickly. If you want a challenge I feel like #378 is ready to go but I have it in draft while I play with it a bit more.

**Comment by markmehere** [comment]
@FlipFloop I try to balance everything with actually wanting to make games sometimes. So keep things pretty chill. 😎

**Comment by FlipFloop** [comment]
@markmehere Ah I see. I just like this project a lot so I wanna help out. I also do want to be able to build for M1...

**Review by CosmoMyzrailGorynych — APPROVED** [review]
👏 (powerclap)

**Comment by CosmoMyzrailGorynych** [comment]
Even my old spaghetti code was dried. Wonderful!

**Pull request merged**
