### PR TITLE
Added Turkish language support

### PR DESCRIPTION
**Pull request by xkral-tr**
I added Turkish language.I hope you add.

Ping @CosmoMyzrailGorynych

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
???

Sorry, I was busy during the holidays and I'm solving all the chores right now. I don't mind adding Turkish language support, and I'm sure others will appreciate it, too.

**Comment by xkral-tr** [comment]
ok

**Comment by xkral-tr** [comment]
but you could tell

**Comment by CosmoMyzrailGorynych** [comment]
I wasn't touching my PC for almost two weeks ¯\\\_(ツ)_/¯

---

Btw, the `develop` branch is for ct.js v2, which is still under development (and will be for months).
v1.5 is at [v1.x branch](https://github.com/ct-js/ct-js/tree/v1.x). If you have time, please prepare an additional PR for this branch so we can publish your translation in a minor release. We recently published a Chinese translation this way.

The translation files will be mostly the same.

**Pull request closed without merging**
