### PR TITLE
:zap: Matter js catmod gravity setting   ⚡Added transparent background checkbox for room and body background color

### PR DESCRIPTION
**Pull request by hunny2000**
Closes #(issue's index).

**Changes proposed in this pull request:**

- it's just a small change exposing gravity x and y on matter js settings page
- Added transparent background checkbox for room 
- Added body background color property in render settings

### CODE REVIEW

**Review by CosmoMyzrailGorynych — CHANGES_REQUESTED** [review]
PR templates exist for a reason.
Also don't just change formatting willy-nilly, it makes reviewing hard to do.

**Comment by hunny2000** [comment]
sorry bout the formatting i use prettier auto formated on save 

what do i need to change here

**Comment by hunny2000** [comment]
it's just a small change exposing gravity x and y on matter js settings page, i had this issue while working gravity being too high made this change for myself in build files, worked perfectly no issues

then wanted to share with anyone else with similar issue, not 100% sure what's the formal process for  requesting pr

**Comment by CosmoMyzrailGorynych** [comment]
Reformatting text files obscures the real changes: https://github.com/ct-js/ct-js/pull/447/files#diff-aca6409d0e446ab01cada4e99d4c678fe0726480d84397d1fb94633bd46e2284

Aaaand bloats git repo a bit, bc it is essentially a fully rewritten file in a git tree. Though the file in question here is small, it's a bad habit.

If you revert the formatting, I will accept the PR.

About PR template, please fill out the first message that is posted with your PR.

**Comment by hunny2000** [comment]
hope it is ok now, sory again for auto formatting is there any other formatting tool you guys use i just turned off prettier for this commit

**Pull request closed without merging**
