### PR TITLE
export to cordova

### PR DESCRIPTION
**Pull request by leedigital**
Cordova export

### CODE REVIEW

**Comment by weekendkoder** [comment]
Does it mean, your are able to build a native app, with cordova ?

**Comment by amsam0** [comment]
I think you can build a android app with this. Not sure if input works.

**Comment by CosmoMyzrailGorynych** [comment]
@leedigital bump
Anything else needed for this PR? We may merge it into v1.4

**Comment by leedigital** [comment]
> Does it mean, your are able to build a native app, with cordova ?

yes, as long as you have the cordova environment installed and configured on your system. I tested the export to compile for android ... but you can also compile for electron, web and etc ...

**Comment by leedigital** [comment]
> @leedigital bump
> Anything else needed for this PR? We may merge it into v1.4

This weekend I will review the code ... But I believe that we can merge it into v1.4

**Comment by weekendkoder** [comment]
interesting ... if you are able to make a native app out of a Javascript game.

**Review by yonderbread — COMMENTED** [review]
This is honestly a fabulous idea.

**Comment by CosmoMyzrailGorynych** [comment]
Closed as a pipeline for exporting projects with Capacitor was implemented in https://github.com/ct-js/ct-js/commit/0f833b7c201bb56a81e0a8bc5a057d8651b7c7e7. Capacitor is a modern alternative to Cordova, though they do have strong overlaps.

**Pull request closed without merging**
