### PR TITLE
:arrow_up: Upgrade to Monaco 0.34

### PR DESCRIPTION
**Pull request by markmehere**
Though it didn't solve the bugs, playing around I did actually notice Monaco became a bit more responsive so this pull request upgrades to Monaco 0.34.

It also includes two other `package.json` related changes:

* The nw.js minimum width and minimum height are increased. Unfortunately nw.js on Mac OS X reverts to these values on occasion, so the very small values are problematic. The toolbar option is obsolete and (in code) nw.js complains of this.
* I don't install `gulp` globally and `npm run lint --fix` will not work. So the second change allows me to not have to add a new script each time I download ct.js.

The `document.getElementById('theLoadingScreen').remove();` is not a typo. For some reason without this change, the Monaco upgrade does not work and the main menu cannot be clicked. This behaviour is quite strange.

### CODE REVIEW

**Comment by markmehere** [comment]
The `renderWhitespace: 'selection'` (default) is causing quite a bit of jitter as the “·” (U+00B7) appears to be wider than the spaces. I will turn off whitespace rendering as a result.

**Comment by markmehere** [comment]
Maybe https://github.com/Microsoft/monaco-editor/issues/648 is the solution?

**Comment by CosmoMyzrailGorynych** [comment]
> The document.getElementById('theLoadingScreen').remove(); is not a typo. For some reason without this change, the Monaco upgrade does not work and the main menu cannot be clicked. This behaviour is quite strange.

what

> The renderWhitespace: 'selection' (default) is causing quite a bit of jitter as the “·” (U+00B7) appears to be wider than the spaces. I will turn off whitespace rendering as a result.

Is it a font-specific issue? Do you have a video to show this problem??

> The nw.js minimum width and minimum height are increased

Pllllease make such things separate PRs in the future

**Comment by markmehere** [comment]
Note the `y` value should be fixed with the latest change...

image
image

**Comment by markmehere** [comment]
> what

I don't really know how to explain it better. Basically you have a huge loading div over the main menu and previously you just made it disappear but didn't remove it.

**Comment by markmehere** [comment]
Shall we revert to 380x380 minimum size? It's nw.js's fault. Although I'm not sure who is using a 380x380 screen at this point. I guess the guy building it on a Raspberry PI. https://github.com/ct-js/ct-js/issues/256 😁

**Comment by CosmoMyzrailGorynych** [comment]
> Shall we revert to 380x380 minimum size?

I think something like 640x400 will be fine. Not that tiny to catch, still small to fit on something bizarre (like an ancient projector in a school).

I think it may also fix problems for those who use UI scaling (vision impairments / requirement to display it onto a wall with the rest of OS' UI)

**Comment by CosmoMyzrailGorynych** [comment]
> I don't really know how to explain it better

The "what" was my shock of that black magic :D

**Review by CosmoMyzrailGorynych — APPROVED** [review]

**Pull request merged**
