### PR TITLE
SVG support 

### PR DESCRIPTION
**Pull request by weekendkoder**
It would be nice to have: SVG support. pixiJS can handle it. Even if its only rasterizing, it makes sense, because of 1x Asset, which handles all resolutions. Otherwise you need to have duplicated assets in different resolutions.

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
Seems that you've misclicked pull requests and issues :D
Issues are created here: https://github.com/ct-js/ct-js/issues/new/choose

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx.

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Comment by weekendkoder** [comment]
Okay. True ... now my request should be in the correct field. Thx..

**Pull request closed without merging**
