### PR TITLE
Issue 121: Add touch controls for catformer and catsteroids

### LINKED ISSUE #121: Demos: add support for touch controls
**Describe the current state of the problem**
Currently, only the ["Memocats"](https://comigo.itch.io/memocats) demo supports running on phones as it does not require keyboard controls. "Catsteroids" and "Catformer" (aka Greed) require them and thus are unplayable on touch devices like phones. As these are the demos of ct.js, they should reflect state-of-the-art features of ct.js, and thus need to be upgraded.

Ct.js now does have easy tools for creating touch-aware games, by its `ct.touch` and `ct.vkeys` modules.

**Describe the solution you'd like**
["Catsteroids"](https://comigo.itch.io/catsteroids) and ["Greed"](https://comigo.itch.io/catformer) should support playing on phones and other touch devices, preferably by adding joysticks (for "Catsteroids") and virtual keys (for both).

### PR DESCRIPTION
**Pull request by amsam0**
Closes #121.

**Changes proposed in this pull request:**

- Added touch controls to catformer 
- Added touch controls to catsteroids (joystick needs testing)

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by amsam0** [comment]
Also we might want to only show the controls on mobile, shouldn't be too hard to hide them

**Comment by amsam0** [comment]
I'm going to add a few changes soon making sure the joystick works and also only show the controls when the user is on mobile. Should I make it just `this.visible = false`, or should I just not create the button and kill the copy? I'm thinking not creating the button, but I'm open to feedback.

**Comment by CosmoMyzrailGorynych** [comment]
The thing is that you can't determine whether a user has mouse or touch controls right at the beginning of the game. Adding main menus may help, as you either click or press the "play" button there and `ct.touch.enabled` can update.

Setting `this.visible = false` will not prevent a player from triggering touch controls, will it?

**Comment by amsam0** [comment]
It will not, now that seems pointless. I think I'll just keep the controls on for now.

**Comment by amsam0** [comment]
I was able to test the controls on mobile, and the shoot button for Catsteroids works, ~~but the joystick doesn't~~ didn't pull your commit. I also added some touch support for the Retry and Start buttons.

For Catformer, the touch controls worked, I also added touch support to the full screen button and the greed screen.

**Comment by amsam0** [comment]
The joystick works, and it looks awesome! I did discover a little bug, maybe with game, not sure. On my mobile device the game froze after I died. The retry screen never shows up. Also I think the retry screen might be a little bugged, not sure. I think this is almost ready to be merged?

**Comment by CosmoMyzrailGorynych** [comment]
Well, almost, yeah.

I had a much weirder bug on mobile: copies of `Laser_Cross_Blue` type got stuck in large groups, but still wiggled horizontally. And horizontal and vertical movement is one block of code in OnStep. Magic... (not something you should care about but wtf is this sorcery)

**Comment by CosmoMyzrailGorynych** [comment]
Catformer is complete; looking into freezing bugs in catsteroids…

**Review by CosmoMyzrailGorynych — APPROVED** [review]

**Pull request merged**
