### PR TITLE
:sparkles: Python installer

### PR DESCRIPTION
**Pull request by amsam0**
Finishes some things in #200.

**Changes proposed in this pull request:**

- Adds a python installer

**Todo**

See https://github.com/naturecodevoid/ct-js/tree/issue-200-installer-python/installer#todo

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by amsam0** [comment]
Status update:
- Windows pyinstaller is working. Just run `./build.bat` to build. 
- Linux _should_ work. Run `./build.sh` to build
- Building the app on Mac works, but running doesnt (for me). Run `./build_mac.sh`
- Dont have time to get travis working, but it should be as easy as installing requirements (`./install-requirements.sh/bat`) and then building it, then taking the built executable (in `./dist/ctjs-installer[.app/.exe]`) and putting it somewhere (like a github release) (this would need python 3 (and preferably 3.7 or 3.8) installed)
- There are some features (such as a rotating in-progress icon and eta) that are more quality of life and I think I can add them when I get back.
- The "Open ct.js" button might not work on platforms other than windows (another QoL)

Hopefully this will help :)

Note: to build for a certain platform you must be on that platform. (Travis will need to run on each OS separately)

Also, here's a good post on python travis: https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems

**Comment by CosmoMyzrailGorynych** [comment]
> Travis will need to run on each OS separately

Oof, it's complicated. Travis works with Linux and Mac only.
Then we probably need a separate repo with prebuilt binaries which can be downloaded by Travis. I sent an invite to ct-js org so you will be able to create a repo there.

**Comment by yonderbread** [comment]
YAYAYAYAYYYAAY

**Comment by amsam0** [comment]
I don't think a separate repo would be needed. Travis works with windows so that's not a problem. Could you explain?

**Comment by CosmoMyzrailGorynych** [comment]
> I don't think a separate repo would be needed. Travis works with windows so that's not a problem. Could you explain?

I feel that rebuilding an installer each time ct.js releases is wrong. The installer may be modified independently of ct.IDE, and in my view, it is better to separate their repos (and pipelines) for easier management and distribution. We always have `wget` in `ct-js` repo and its `.travis.yml` file :D so bundling it inside GitHub or itch.io releases won't be an issue. And on the site, we can put a link to the latest version of the installer.

**Comment by amsam0** [comment]
I'll make a repo on my account for the installer, when it's working I can change the owner to the ct-js org

Repo: https://github.com/naturecodevoid/ct-js-installer

**Pull request closed without merging**
