### PR TITLE
:zap: Adds ct.onStepMultiplier and ct.whichOnStep

### PR DESCRIPTION
**Pull request by markmehere**
This one is going to stay in draft for a bit and while I test it.

Basically the aim is rather than execute `onStep` once per loop with a `ct.delta` value, this executes it `ct.delta * ct.onStepMultiplier` times (if `ct.onStepMultiplier` is positive).

This should improve performance of some action/arcade games.

The problem is because the pressed value may be true on multiple iterations, multiple shots may be fired. To overcome this `ct.whichOnStep` is provided and the developer can restrict firing to when an action is pressed and `ct.whichOnStep === 0`.

In my initial implementation, every item was evaluated *n* times before the next. In the revised implementation, every item should be evaluated one after the other *n* times.

It's this revision I need to test.

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
So it's like time dilation?

**Review by CosmoMyzrailGorynych — COMMENTED** [review]
The use of ct.delta is confusing 😵‍💫 What's your approach for it?

**Comment by CosmoMyzrailGorynych** [comment]
@markmehere I thought about ways to add built-in time dilation, and an approach I thought about was making several ct.loop passes bound to different PIXI tickers. There can be a regular one, one that performs exactly 30fps, 10fps, 1fps. That's how it is built in Space Engineers scripting. (wow what a wild reference here)

ct.loop is then split into an OnStep pass and OnDraw pass. Copies are assigned to specific ticker by being put to, say, ct.stack, ct.stack30, ct.stack10, ct.stack1. A copy is always in exactly one stack. During a ticker trigger, an appropriate stack is iterated upon, with ct.delta being relative to full FPS (ct.stack's is 1, ct.stack30's is 2 and so on). Draw events are performed for all the stacks each frame.

* The last thing can be a toggle: to dilate the Draw event or not can be up to a user.
* If set to off, users can interpolate movement and such with their own logic.
  * Or maybe with a built-in function as well!

**Comment by markmehere** [comment]
I think you're on the right track. But the problem is confusing and really hard. I spent half-a-day on it and discovered many bugs in Maelstrom as a result:

https://markmehere.itch.io/maelstrom

The main purpose of the PR is small object collisions. You mentioned in the documentation the difficulty with bullets passing through thin walls. Having two fast-moving small objects collide proves more difficult. By doing several calculations per frame you have a greater chance of nailing those small object collisions.

The following shows a bullet travelling top-to-bottom and a small asteroid travelling left-to-right. When the onStepMultiplier is 2, the objects collide. But when the onStepMultiplier is 0 (not enabled) the bullet and asteroid pass through one another even though instinctively we know they collide.

https://github.com/ct-js/ct-js/assets/52765023/4531791c-7a3f-4755-bbef-b28f040e3f4a

My problem with separate timers is I've really liked the way ct.js does input. JavaScript solved a whole lot of multithreading issues by staying single-thread only. I similarly think ct.js solves a whole lot of issues by doing one-timer only.

**Comment by markmehere** [comment]
My brain is absolutely fried after that - so hopefully I haven't accidentally introduced any bugs into Maelstrom or the PR. The PR will stay in draft for a bit yet until I confirm it works.

**Comment by markmehere** [comment]
And you are spot on. It's not just a small objects thing. It also helps if the game drops a lot of frames due to big load or something.

**Comment by CosmoMyzrailGorynych** [comment]
Needs further thought. Postponing for now.
Issues with colliding with small objects should be solved with collision shape sweeping instead.
Time dilation to optimize stuff needs more thought on how it can be used in gameplay-important templates. Need to make checks for off-bounds copies that is not slower than just running code. This all probably needs collision system update.

**Pull request closed without merging**
