### PR TITLE
[WIP] :sparkles: File-based ct.js structure

### LINKED ISSUE #75: Organize assets with folders
# Meta

This issue covers:

* a new asset browser that supports folders with projects' hierarchical file-based structure
* multi-tabbed view (one asset = one tab; multiple assets of one type can be opened) (#48)
* changes in internal APIs that make the above stuff possible
* re-write of asset pickers. Will reuse the asset browser component.

# Links

* ~~The spec and working draft of internal working of the  file-based structure:
   https://docs.google.com/document/d/1qc1VOMZw4ddV2O4VCzbMncZP1HajTU1oK6Rjwz4Tlog/edit?usp=sharing~~ outdated as heck
* Mockups of the interface: 
  https://www.figma.com/file/5ranH0vsypOnCYGIKntGVF/Ct.js-v2?node-id=0%3A1
* WIP branch: 
  ~~https://github.com/ct-js/ct-js/tree/issue-75-asset_folders~~
  https://github.com/ct-js/ct-js/tree/unified-assets
* Discuss on Discord:
   https://discord.gg/kHWwDvQjrb

### PR DESCRIPTION
**Pull request by amsam0**
Closes #75.

**Changes proposed in this pull request:**

- File-based ct.js structure

**Things to do:**

- [x] Fix loading/saving system
- [x] Skeletons? **(how to define them?)**
- [ ] Font data (also move images from `project/fonts`) **(what controls this?)**
- [ ] Image data (also move images from `project/img`) **(what controls this?)**
- [ ] Sound data (also move sounds from `project/snd`) **(what controls this?)**
- [x] `contents` folder (has all files/folders like `sounds`, `Actions.yaml`, etc.) (maybe optional?)
- [x] `scripts` folder (maybe the contents should be added to html or added to the scripts?) (they could be treated as node modules)
  - You should be able to add a library and that library gets push to the scripts array
    - This makes it easy to paste a library like jquery in the folder without having to use akatemplate, even though that is definitely the better option 😛, having a big library randomly in the export probably wouldn't be good for performance
- [x] Scripts folder outside `contents` folder
- [ ] ~~node support (`package.json`, `node_modules`, etc.)~~
- [x] everything in one folder ~~(`.ict` and `.ict.recovery` in the same folder as the `contents` folder)~~
- [x] `.gitignore` (should be created with a project or we will see repos with `node_modules` uploaded to GitHub.)
- [ ] Separate emitter tandems into `.data` folder?
- [ ] Some files should be JSON format?
- [ ] Images, fonts, sounds, thumbnails in `.data` folder
- [ ] **Open folder space, with files read by extension** (this allows for easy folder organization showed in #75)

See https://docs.google.com/document/d/1qc1VOMZw4ddV2O4VCzbMncZP1HajTU1oK6Rjwz4Tlog.

### CODE REVIEW

**Comment by amsam0** [comment]
I've tested this with catsteroids and everything seemed to work well. 😄

**Comment by amsam0** [comment]
A guide to migrating your project will be needed. I can migrate catsteroids by doing:

1. Move `catsteroids.ict` to `catsteroids/catsteroids.ict`
1. Open `catsteroids/catsteroids.ict` and save

A migration script or something else could be made to automate this process.

**Comment by CosmoMyzrailGorynych** [comment]
> Skeletons? (how to define them?)

I think in the same fashion as textures. A metadata file (that has info about source file provider) and a folder with source files + thumbnails.

> Font data (also move images from project/fonts) (what controls this?)
> Image data (also move images from project/img) (what controls this?)
> Sound data (also move sounds from project/snd) (what controls this?)

Could you elaborate??

> Some files should be JSON format?

Not required, but it will speed up browsing in some cases. I wrote about it here:
изображение

The idea is that sounds may differ visually in the content browser (we have "music" and generic "wave" icons now), and to get the data for this differentiation, we will need to hot-load their metadata file right in the content browser's methods. The same goes for fonts as weight and style are what make them unique in one typeface. This all applies unless some means are made to remove these additional fs calls.

But maybe it won't be needed at all if YAML will be fast enough (needs stress-testing).

> Separate emitter tandems into .data folder?

It doesn't seem to me to add any value.

**Comment by amsam0** [comment]
Thanks for the feedback. What I meant about the font/image/sound was that I was wondering where/what controls that (`project/img`, `project/snd`, `project/fonts`) and what I need to change to complete that task. I do like it outside the `contents` folder though; which one do you prefer?

**Comment by CosmoMyzrailGorynych** [comment]
> What I meant about the font/image/sound was that I was wondering where/what controls that 

I guess I should test the PR branch first to understand :upside_down_face: 

> I do like it outside the contents folder though; which one do you prefer?

Noooo-no-no-no, contents are contents, and fonts, sounds and images should be in `project/contents/` as well.
For migration purposes (thinking about a free folder-based organization), it would be nice if there were folders `project/content/textures`,  `project/content/sounds`, etc, so resources don't end up in one huge pile.

**Comment by CosmoMyzrailGorynych** [comment]
> having a big library randomly in the export probably wouldn't be good for performance

If it gets stitched in one file with the game (current v1.2.1/1.3.0 behavior), then it only reduces the number of web requests, which is good.

A button "Import from file" in the scripts section will be handy.

**Comment by CosmoMyzrailGorynych** [comment]
> node support (package.json, node_modules, etc.)

Definitely out of scope rn; see https://github.com/orgs/ct-js/projects/2

**Comment by amsam0** [comment]
To rephrase my question, what code do I change to change the location of the images, sounds, and fonts? I've tried before and had a lot of trouble.

**Comment by CosmoMyzrailGorynych** [comment]
Those are usually hard-coded in the tags relevant to this and that entity. `sounds-panel` and `sound-editor`, `textures-panel` and `texture-editor`, etc.

It is a good time to separate asset-finding logic and put it in map-like js files, as there soon will be more data types.

**Comment by amsam0** [comment]
I'll work on this now. What are "map-like js files?" Are they like .map.js?

Edit: Do you know if theres a riot autocomplete extension for vscode? I couldnt find one

**Comment by CosmoMyzrailGorynych** [comment]
No, I meant that for future content browser and better organization of shared logic of different asset types, there should be several shared modules that separate common resource logic from presentation.  For example, to get a human-readable name of an asset type, a thumbnail, as well as specific inner APIs like textures currently have (see `src/node_requires/resources/textures`). And then those name/thumbnail getters should be accessible from objects like `nameGetters[resourceType]`. This will make coding future content browser easier, and will make current tag `asset-viewer` less reliant on outer code.

Riot: nope, I only have default autocompletions based on previously written words. I can't get a link rn but it is a Riot extension with "Riot (jade)" syntax mode.

**Comment by amsam0** [comment]
Sounds good.

I have the riot (jade) syntax.

**Comment by CosmoMyzrailGorynych** [comment]
For the record, this PR and #75 are made in https://github.com/ct-js/ct-js/tree/issue-75-asset_folders branch.

**Pull request closed without merging**
